# Generated by Django 2.0.2 on 2018-03-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text='Есімің еңгізіңіз', max_length=50)),
                ('LastName', models.CharField(help_text='Тегін еңгізіңіз', max_length=50)),
                ('Email', models.CharField(help_text='Почтасын еңгізіңіз', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Phone', models.CharField(help_text='20 саннан тұрады. Телефон нөмерін еңгізіңіз', max_length=20, verbose_name='Phone')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Қаланың атын еңгізіңіз', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ManyToManyField(help_text='Select a location for this employee', to='catalog.Location'),
        ),
    ]
